### ISSUE TITLE
In Code v1.19, shows up on every closed tab, not only last one

### ISSUE THREAD

**Issue by brunetton** [artdiniz/quit-control-vscode#10]
Hi, 

I used this plugin for quite a while and I was really happy with. 
But since some time (maybe after some VScode updates), the confirm dialog appears not only when closing the last tab, or when triggering `quit` shortkey (witch is what we want it to do), but also when closing a tab, but not the last one (witch is not what we want).

Did anyone else noticed this too ? 

Thanks

**Comment by artdiniz** [comment]
I noticed that too. I'll be taking a look at it today :)

**Comment by brunetton** [comment]
Wonderful ! Thanks! You'll make my day :-)

Le 20 janv. 2018 00:00, "Artur Diniz Adam" <notifications@github.com> a
écrit :
