### ISSUE TITLE
command 'quitPlugin.keybindings.closeWindow' not found (also quit and closeEditor)

### ISSUE THREAD

**Issue by richarddewit** [artdiniz/quit-control-vscode#12]
### Steps to reproduce:

1. Install `Quit Control for VSCode`
2. Press either <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>W</kbd> - or - <kbd>Ctrl</kbd>+<kbd>W</kbd> - or - <kbd>Ctrl</kbd>+<kbd>Q</kbd> in an editor or system tab
3. Message pops up saying `command 'quitPlugin.keybindings.closeWindow' not found` (or `quit` or `closeEditor`)

### Extension information:

> Name: Quit Control for VSCode
> Id: artdiniz.quitcontrol-vscode
> Description: Stop mistyping keyboard shortctus that close/quit VSCode unintentionally
> Version: 3.1.0
> Publisher: Artur Diniz Adam
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=artdiniz.quitcontrol-vscode

### VSCode version:

```
$ code -v
1.32.3
a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
x64
```

**Comment by dotpointer** [comment]
This happens to me too. I can no longer close open files with `Ctrl + W`, I only get `command 'quitPlugin.keybindings.closeEditor' not found` in the bottom right.

Edit, adding info:

```
Version: 1.33.0
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:08:57.775Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64
```

Edit: I disabled the extension, did not help, had to uninstall to get `Ctrl+W` back.

**Comment by sasa-friedrich-bitlab** [comment]
I can also confirm.

> Quit Control for VSCode 2019-03-16 (v3.1.0)

> VSCode
Version: 1.33.0
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:08:57.775Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.4.0-138-generic

**Comment by Shineeeee** [comment]
I have same issue.

**Comment by artdiniz** [comment]
I could only replicate this in Ubuntu 18.04.  Can't say if it was happening in other Linux distros. 
I couldn't replicate this issue in macOS nor Windows. Both were functional.

Did some work on it and tested the fix in a Vscode 1.32/Ubuntu 18.04 VirtualBox VM 🙂 Releasing the fix right now in 3.1.1. If you update, please let me know if it's working for you.

**Comment by dotpointer** [comment]
I am running 3.1.1 right now and I am still getting the error "command 'quitPlugin.keybindings.closeEditor' not found" when I do Ctrl+W.

@artdiniz Should the issue be reopened or should a new one be created? I cannot reopen.

**Comment by sasa-friedrich-bitlab** [comment]
I can confirm same error after update

**Comment by artdiniz** [comment]
Thanks for the feedback! I'm reopening this one @dotpointer.

**Comment by thiagobraga** [comment]
Hi @artdiniz. I think I've found the problem. I've made a [PR](https://github.com/artdiniz/quit-control-vscode/pull/14) which I think can solve the problem. 🙂

I've tested locally in Ubuntu 18.04 and Mac OS Mojave 10.14.4. In Ubuntu, if the file name is different from the one in `out/index.js`, then the extension does not work, generating the error `command 'quitPlugin.keybindings.closeWindow' not found`. For example:

### Ubuntu 18.04

Files `CloseAll.js` and `index.js` (as packaged in the vsix file)
```
// index.js
var closeAll_1 = require("./closeAll");
```
This doesn't work. But renaming `CloseAll.js` to `closeAll.js` and restarting VS Code, makes the extension works again.

### Mac OS Mojave 10.14.4

In Mac OS the extension works normally. I've renamed `CloseAll.js` to `CLOSEALL.js` and restarted VS Code, the extension continued working. It only stops working when requiring wrong filename (for example with typo `closeAlll.js`).

**Comment by artdiniz** [comment]
Thank you @thiagobraga, for pointing it out!

Bad file names in vsix package were causing the issue. 
#15 fixed this in the build process before publishing to the marketplace.

Fix will be released in 3.1.2 :)
Please let me know if this fixed the issue for you!

**Comment by dotpointer** [comment]
Works for me now, thanks.

**Comment by ericgoe** [comment]
I just had this issue in the following version on MacOS.

```bash
$ code -v
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

I fixed it by completely quiting vscode and restart it.
