### ISSUE TITLE
Support for Any Chord?

### ISSUE THREAD

**Issue by macintacos** [artdiniz/quit-control-vscode#18]
I have a keymap that heavily relies on chord called [Chord Heavy](https://marketplace.visualstudio.com/items?itemName=vscode-macintacos.chord-heavy-keymap), and while I think that it's great, the discoverability of key chords kinda sucks because of the following issue in VSCode that hasn't been addressed: https://github.com/microsoft/vscode/issues/3969

I think that this extension could do wonders for key chord discoverability if it could just be invoked whenever you start executing a chord. This extension has the potential to become VSCode's very own [which-key](https://github.com/justbur/emacs-which-key) with a little imagination :)

**Comment by artdiniz** [comment]
In think this one is amazingly handled by [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode)
