### ISSUE TITLE
Works great but what about Alt+ F4

### ISSUE THREAD

**Issue by delrius-euphoria** [artdiniz/quit-control-vscode#19]
It would be great if you could stop exiting through Alt+ F4 for windows as that is more common than Ctrl + W

**Comment by artdiniz** [comment]
a time ago I got to the conclusion that it couldn't be done at all by this extension alone. I might be wrong, but what I understood is that the `Alt + F4` event happens in the OS level, long before VSCode itself could handle it, which puts the extension in a bad place for this one. Maybe a companion native windows "app" could do it 🤔 

I won't be able to go after this for now, but maybe someone that get to this issue in the future might be eager to implement it 🤞

**Comment by delrius-euphoria** [comment]
I guess that's the reason, though there is some option to ask before closing if a terminal is open, which I am using now. Thanks!
