### ISSUE TITLE
Typos in project about

### ISSUE THREAD

**Issue by Relequestual** [artdiniz/quit-control-vscode#20]
Can't PR fix it, but the project about on the github repo has two typos.
`shortctus` -> `shortcuts`.
`quiting` -> `quitting`.

Minor, but still. =]

Thanks for your hard work in providing this extension!

**Comment by artdiniz** [comment]
thank you so much for noticing this one 🙏 

The description on `package.json` and therefore VSCode marketplace were wrong too 😬😅

**Comment by Relequestual** [comment]
More than welcome. Typos are easy to fix and make things nicer for everyone.
=]
