### ISSUE TITLE
Unable to quit after closing all windows

### ISSUE THREAD

**Issue by OliverJAsh** [artdiniz/quit-control-vscode#24]
1. Open a single VS Code window
2. Close window and confirm
3. With no VS Code windows left open, VS Code should still be running. It should be possible to quit by pressing `command+q` but this doesn't work.

**Comment by artdiniz** [comment]
This one is so annoying 😞 I didn't have a clue on how to solve it till now! But I think this issue inspired me 😆 
Will be fixed on next release `3.2.0`.
