### ISSUE TITLE
no issue, just OMG THANK YOU

### ISSUE THREAD

**Issue by shudson-versasuite** [artdiniz/quit-control-vscode#28]
Looks like they closed commenting on this
https://github.com/microsoft/vscode/issues/54492

After new update, VSCode started closing app on CTRL-W when no editors are open.  AGAIN.  It took me forever the last time to override all the default CTRL-W mappings.  I followed all the directions on that issue 54492 thread, and still no.  Most likely because they reintroduced the bug feature AGAIN.

You saved me the next three hours of banging my head against the desk.  You deserve an award.

**Comment by artdiniz** [comment]
I'm glad it helped you =)
